//
//  WelcomeInteractor.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic
{
    func login(request: Welcome.Login.Request)
}

protocol WelcomeDataStore
{
    //var name: String { get set }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore
{
    var presenter: WelcomePresentationLogic?
    var worker: WelcomeWorker?
    //var name: String = ""
    
    // MARK: login
    
    func login(request: Welcome.Login.Request)
    {
        
        worker?.login(email: request.email, password: request.password) { (success) in
            
            let response = Welcome.Login.Response(success: success)
            self.presenter?.presentLogin(response: response)
        }
    }
}
