//
//  WelcomePresenter.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomePresentationLogic
{
    func presentLogin(response: Welcome.Login.Response)
}

class WelcomePresenter: WelcomePresentationLogic
{
    weak var viewController: WelcomeDisplayLogic?
    
    // MARK: Do something
    
    func presentLogin(response: Welcome.Login.Response) {
        let viewModel = Welcome.Login.ViewModel()
        viewController?.displayLogin(viewModel: viewModel)
    }
}
