//
//  ListStoreProductsInteractorTests.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import zmani
import XCTest

class ListStoreProductsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListStoreProductsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListStoreProductsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListStoreProductsInteractor()
  {
    sut = ListStoreProductsInteractor()
  }
  
  // MARK: Test doubles
  
  class ListStoreProductsPresentationLogicSpy: ListStoreProductsPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ListStoreProducts.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ListStoreProductsPresentationLogicSpy()
    sut.presenter = spy
    let request = ListStoreProducts.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
