//
//  ListStoreProductsPresenterTests.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import zmani
import XCTest

class ListStoreProductsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListStoreProductsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListStoreProductsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListStoreProductsPresenter()
  {
    sut = ListStoreProductsPresenter()
  }
  
  // MARK: Test doubles
  
  class ListStoreProductsDisplayLogicSpy: ListStoreProductsDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: ListStoreProducts.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = ListStoreProductsDisplayLogicSpy()
    sut.viewController = spy
    let response = ListStoreProducts.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
