//
//  ListStoresPresenterTests.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import zmani
import XCTest

class ListStoresPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: ListStoresPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupListStoresPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupListStoresPresenter()
    {
        sut = ListStoresPresenter()
    }
    
    // MARK: Test doubles
    
    class ListStoresDisplayLogicSpy: ListStoresDisplayLogic
    {
        var displayStoresCalled = false
        
        func displayFetchedStores(viewModel: ListStores.FetchStores.ViewModel)
        {
            displayStoresCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentFetchedStoresShouldAskViewControllerToDisplayStores()
    {
        // Given
        let spy = ListStoresDisplayLogicSpy()
        sut.viewController = spy
        let response = ListStores.FetchStores.Response()
        
        // When
        sut.presentFetchedStores(response: response)
        
        // Then
        XCTAssertTrue(spy.displayStoresCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
