//
//  ListStoresWorker.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListStoresWorker
{
    func fetchStores(completionHandler: @escaping ([Store]) -> Void)
    {
        let store = [
            Store(name: "ZARA", image: "zara"),
            Store(name: "adidas", image: "adidas"),
            Store(name: "H&M", image: "hm"),
            Store(name: "Lacoste", image: "lacoste"),
            Store(name: "Levis", image: "levis"),
            Store(name: "Nike", image: "nike"),
            Store(name: "Tom Ford", image: "tomford"),
            Store(name: "ZOMA", image: "zoma"),
        ]
        completionHandler(store)
    }
}
