//
//  ListStoresPresenter.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoresPresentationLogic
{
    func presentFetchedStores(response: ListStores.FetchStores.Response)
}

class ListStoresPresenter: ListStoresPresentationLogic
{
    weak var viewController: ListStoresDisplayLogic?
    
    
    func presentFetchedStores(response: ListStores.FetchStores.Response)
    {
        
        var displayedStores: [ListStores.FetchStores.ViewModel.DisplayedStore] = []
        for store in response.fetchedStores {
            let title = store.name
            let image = store.image
            let displayedStore = ListStores.FetchStores.ViewModel.DisplayedStore(title: title, image: image)
            displayedStores.append(displayedStore)
        }
        let viewModel = ListStores.FetchStores.ViewModel(displayedStores: displayedStores)
        viewController?.displayFetchedStores(viewModel: viewModel)
    }
    
    
    
}
