//
//  ListStoresInteractor.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoresBusinessLogic
{
    func fetchStores(request: ListStores.FetchStores.Request)
}

protocol ListStoresDataStore
{
    //var name: String { get set }
}

class ListStoresInteractor: ListStoresBusinessLogic, ListStoresDataStore
{
    var presenter: ListStoresPresentationLogic?
    var worker = ListStoresWorker()
    
    func fetchStores(request: ListStores.FetchStores.Request)
    {
        worker.fetchStores() { [weak self] (stores) in
            let response = ListStores.FetchStores.Response()
            self?.presenter?.presentFetchedStores(response: response)
        }
    }
}
