//
//  ListStoresPresenter.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoresPresentationLogic
{
    func presentFetchedStores(response: ListStores.FetchStores.Response)
}

class ListStoresPresenter: ListStoresPresentationLogic
{
    weak var viewController: ListStoresDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedStores(response: ListStores.FetchStores.Response)
    {
        let viewModel = ListStores.FetchStores.ViewModel()
        viewController?.displayFetchedStores(viewModel: viewModel)
    }
    
}
