//
//  ListStoresWorker.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListStoresWorker
{
    func fetchStores(completionHandler: @escaping ([Store]) -> Void)
    {
        let store = Store(name: "zara", image: "zara")
        completionHandler([store])
    }
}
