//
//  WelcomeViewControllerTests.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import zmani
import XCTest

class WelcomeViewControllerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: WelcomeViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupWelcomeViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupWelcomeViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = (storyboard.instantiateViewController(withIdentifier: "WelcomeViewController") as! WelcomeViewController)
    }
    
    func loadView()
    {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class WelcomeBusinessLogicSpy: WelcomeBusinessLogic
    {
        var loginCalled = false
        
        func login(request: Welcome.Login.Request)
        {
            loginCalled = true
        }
    }
    
    // MARK: Tests
    
    func testLoginWhenViewIsLoaded()
    {
        // Given
        let spy = WelcomeBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.loginCalled, "viewDidLoad() should ask the interactor to do something")
    }
    
    func testDisplayLogin() {
        // Given
        let viewModel = Welcome.Login.ViewModel()
        
        // When
        
        loadView()
        sut.displayLogin(viewModel: viewModel)
        XCTAssert(viewModel != nil, "displayLogin called")
    }
    
}
