//
//  WelcomePresenterTests.swift
//  DonnaApp
//
//  Created by Irakli on 11/15/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import zmani
import XCTest

class WelcomePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: WelcomePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupWelcomePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupWelcomePresenter()
  {
    sut = WelcomePresenter()
  }
  
  // MARK: Test doubles
  
  class WelcomeDisplayLogicSpy: WelcomeDisplayLogic
  {
    var displayLoginCalled = false
    
    func displayLogin(viewModel: Welcome.Login.ViewModel)
    {
        displayLoginCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentLoginShouldAskViewControllerToDisplayResult()
  {
    // Given
    let spy = WelcomeDisplayLogicSpy()
    sut.viewController = spy
    let response = Welcome.Login.Response(success: false)
    
    // When
    sut.presentLogin(response: response)
    
    // Then
    XCTAssertTrue(spy.displayLoginCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
