//
//  ListStoreProductsWorker.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class ListStoreProductsWorker
{
    
    func fetchProducts(forStore store: String, completionHandler:@escaping([StoreProduct]) -> Void)
    {
        let storeProducts = [
            StoreProduct(name: "T-Shirt", image: "tshirt", price: 100, size: .M, Sex: .M, discountedPrice: 50, discount: 50, category: [.Shirt]),
            StoreProduct(name: "T-Shirt", image: "tshirt", price: 100, size: .M, Sex: .M, discountedPrice: 100, discount: 70, category: [.Shirt]),
            StoreProduct(name: "T-Shirt", image: "tshirt", price: 30, size: .M, Sex: .M, discountedPrice: 15, discount: 50, category: [.Shirt])
        ]
        completionHandler(storeProducts)
    }
    
}
