//
//  ListStoreProductsPresenter.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoreProductsPresentationLogic
{
  func presentSomething(response: ListStoreProducts.Something.Response)
}

class ListStoreProductsPresenter: ListStoreProductsPresentationLogic
{
  weak var viewController: ListStoreProductsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListStoreProducts.Something.Response)
  {
    let viewModel = ListStoreProducts.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
