//
//  ListStoreProductsWorker.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListStoreProductsWorker
{
  
    func fetchProducts(forStore store: String, completionHandler:@escaping([StoreProduct]) -> Void)
    {
        let storeProducts = StoreProduct.DummyStoreProducts
        completionHandler(storeProducts)
    }
    
}
