//
//  ListStoreProductsInteractor.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoreProductsBusinessLogic
{
  func doSomething(request: ListStoreProducts.Something.Request)
}

protocol ListStoreProductsDataStore
{
  //var name: String { get set }
}

class ListStoreProductsInteractor: ListStoreProductsBusinessLogic, ListStoreProductsDataStore
{
  var presenter: ListStoreProductsPresentationLogic?
  var worker: ListStoreProductsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListStoreProducts.Something.Request)
  {
    worker = ListStoreProductsWorker()
    worker?.doSomeWork()
    
    let response = ListStoreProducts.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
