//
//  ListStoreProductsPresenter.swift
//  zmaniApp
//
//  Created by Irakli on 11/18/19.
//  Copyright (c) 2019 Irakli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListStoreProductsPresentationLogic
{
    func presentProducts(response: ListStoreProducts.FetchStoreProducts.Response)
}

class ListStoreProductsPresenter: ListStoreProductsPresentationLogic
{
    weak var viewController: ListStoreProductsDisplayLogic?
    
    // MARK: Do something
    
    func presentProducts(response: ListStoreProducts.FetchStoreProducts.Response)
    {
        let viewModel = ListStoreProducts.FetchStoreProducts.ViewModel(displayedStoreProducts: ListStoreProducts.FetchStoreProducts.ViewModel.DummyDisplayedStoreProducts)
        viewController?.displayProducts(viewModel: viewModel)
    }
}
